"""Automated execution module (patent ref: 116).

Applies validated remediations by opening a pull request (never pushes directly
to a protected branch) via the GitHub API.
"""
from __future__ import annotations
import requests
from dataclasses import dataclass
from src.remediation.remediation_generator import Remediation
from src.validation.sandbox_validator import ValidationResult

@dataclass
class ExecutionResult:
    opened_pr: bool
    pr_url: str | None
    message: str


def execute_remediation(
    remediation: Remediation,
    validation: ValidationResult,
    repo: str,
    token: str,
    base_branch: str = "main",
) -> ExecutionResult:
    if not validation.passed:
        return ExecutionResult(False, None, "Remediation failed sandbox validation; not applied.")

    branch_name = f"auto-remediation/{remediation.root_cause}"
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}

    # Create branch, commit patch, open PR (calls kept minimal/illustrative).
    pr_payload = {
        "title": f"Auto-remediation: {remediation.description}",
        "head": branch_name,
        "base": base_branch,
        "body": (
            f"Automated fix generated by the predictive CI/CD remediation system.\n\n"
            f"Root cause: {remediation.root_cause}\nValidation output:\n```\n{validation.output[:1500]}\n```"
        ),
    }
    resp = requests.post(
        f"https://api.github.com/repos/{repo}/pulls", json=pr_payload, headers=headers, timeout=30
    )
    if resp.status_code == 201:
        return ExecutionResult(True, resp.json().get("html_url"), "PR opened successfully.")
    return ExecutionResult(False, None, f"Failed to open PR: {resp.status_code} {resp.text}")
